### ISSUE TITLE
implement upgradable contracts

### ISSUE THREAD

**Issue by normadn** [frens-pool/frens-contracts#4]

**Comment by 0xWildhare** [comment]
there are two items that need to be addressed, one is the transparent proxy, which is an action item in a later phase of the project - this should be as easy as defining the user-facing contracts that we would like the proxies for (likely the pool and the factory, probably not the NFT) deploying and linking them. The other is upgradability of the contracts that are not user facing. I think one of the near term steps should be to start building that infrastructure in the contracts (possibly modeling after the rocket pool design). I am renaming this project to "implement upgradable contracts" assuming we will create a project to implement the transparent proxies when the time comes. if there are strong opinions on the methods used to allow the contracts to be upgraded, please comment here.

**Comment by 0xWildhare** [comment]
upgradeable contracts deployed on goerli:

FrensPoolShare:
0x30938d55B18C1273FD7f5901a2B33127c01cB371
StakingPoolFactory:
0x38ED69e7635ADB2083B06c5d00B9fb9C7e55CD34
storage:
0x3703511A5fa20Be3FdBAD50A0A84d5d87E7683F4
initializer:
0x10B7522A2Fe86891e2739AAb817bb3185508Eaa1
FrensMetaHelper:
0xA31171a97550a122b4175F312955768222f48dFD
FrensPoolShareTokenURI:
0x473C31235BA30781C966a14995b3d09941d196AE
FrensArt:
0xb1d85eB29376E596E613be1fC73d3ef8c5A608aa
