### ISSUE TITLE
research fractionalizing NFTs

### ISSUE THREAD

**Issue by normadn** [frens-pool/frens-contracts#5]
context: https://www.partybid.app/buy/0x466615e7e6461e4138d11902dd0101c9bf67db3c

**Comment by 0xWildhare** [comment]
There is nothing in out code that prevents a user from depositing 32 eth in one pool, then fictionalizing that nft on whichever platform they choose.  if this is an option that users want it is available, so we get the best of both worlds leaving it open and flexible as is.

**Comment by normadn** [comment]
makes sense. Thx for clarifying!
